slam_toolbox:
  ros__parameters:
    use_sim_time: true            # Gazebo 時鐘
    odom_frame: odom
    map_frame: map
    base_frame: base_link         # 若需要可改 base_footprint
    scan_topic: /scan
    resolution: 0.05              # 地圖解析度 (m/cell)
    minimum_time_interval: 0.1
    map_update_interval: 1.0
    enable_interactive_mode: false
    mode: mapping
