name: ROS2 CI (Foxy, self-hosted no-setup-ros)

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, wsl]   # 你的自有 runner 標籤
    timeout-minutes: 60
    env:
      DEBIAN_FRONTEND: noninteractive
      AMENT_TRACE_SETUP_FILES: "0"

    steps:
      - uses: actions/checkout@v4

      # ---- 1) 基本環境（顯示完整輸出，容易除錯）----
      - name: Preflight APT & locale
        shell: bash
        run: |
          set -euxo pipefail
          echo 'Etc/UTC' | sudo -n tee /etc/timezone
          sudo -n apt-get update
          sudo -n apt-get install -y curl gnupg2 locales lsb-release
          sudo -n locale-gen en_US en_US.UTF-8
          sudo -n update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
          locale
          lsb_release -a || true

      # ---- 2) 加入 ROS2 Foxy 套件庫並安裝 ----
      - name: Install ROS 2 Foxy
        shell: bash
        run: |
          set -eo pipefail
          # 金鑰 & 套件庫
          curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo -n apt-key add -
          echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo -n tee /etc/apt/sources.list.d/ros2-latest.list
          sudo -n apt-get update
          # 你要的是能 build 就好；若空間夠也可裝 ros-foxy-desktop
          sudo -n apt-get install -y ros-foxy-ros-base python3-colcon-common-extensions python3-rosdep
          # 初始化 rosdep（第一次可能會 warn，無妨）
          sudo -n rosdep init || true
          rosdep update

      # ---- 3) 用 rosdep 解析專案相依（非 ROS 套件）----
      - name: rosdep install
        shell: bash
        run: |
          set -eo pipefail
          source /opt/ros/foxy/setup.bash
          rosdep install --from-paths src --ignore-src -r -y

      # ---- 4) 建置 ----
      - name: colcon build
        shell: bash
        run: |
          set -exo pipefail
          source /opt/ros/foxy/setup.bash
          colcon build --event-handlers console_direct+ --symlink-install
